apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1 # number of pods you want to run
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: karakocberkay/auth:latest
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          ports:
            - containerPort: 5000 # the port your app is listening on
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
